# Generated by Django 2.2.6 on 2020-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_standardisation', '0002_auto_20200413_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='voltage',
            field=models.CharField(choices=[('6kV', 'niskie'), ('15kV', 'średnie'), ('30kV', 'średnie'), ('110kV', 'wysokie')], default='6kV', max_length=5),
        ),
    ]
