# Generated by Django 2.2.6 on 2020-04-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_standardisation', '0003_warning_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='voltage',
            field=models.IntegerField(choices=[(1, '6kV'), (2, '15kv'), (3, '30kv'), (4, '110kV'), (5, 'Puste')], default=5, max_length=5),
        ),
    ]
