# Generated by Django 2.2.6 on 2020-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_standardisation', '0005_auto_20200413_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('warning', models.ManyToManyField(to='warnings_standardisation.Warning')),
            ],
        ),
    ]
