# Generated by Django 2.2.6 on 2020-04-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_standardisation', '0006_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='warning',
        ),
        migrations.AddField(
            model_name='warning',
            name='direction',
            field=models.ManyToManyField(to='warnings_standardisation.Direction'),
        ),
    ]
