# Generated by Django 2.2.6 on 2020-04-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_standardisation', '0007_auto_20200416_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='voltage',
        ),
    ]
