# Generated by Django 2.2.6 on 2020-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_standardisation', '0008_remove_warning_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='warning',
            name='voltage',
            field=models.ManyToManyField(to='warnings_standardisation.Voltage'),
        ),
    ]
